<a href="https://colab.research.google.com/github/nnnagle/pytorch-demo/blob/main/pytorch_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# Clone your new repo into Colab
!git clone https://github.com/nnnagle/pytorch-demo.git
%cd pytorch-demo

# Configure Git user
!git config --global user.email "nnnagle@gmail.com"
!git config --global user.name "Nicholas Nagle"


Cloning into 'pytorch-demo'...
/content/pytorch-demo


In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9952, 0.1525],
        [0.6703, 0.8602]]) 



Use shape to set the size of a tensor.

In [4]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1070, 0.0102, 0.4014],
        [0.7321, 0.4981, 0.6765]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor Attributes:

In [5]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Move to a cuda. Don't forget in Colab to Edit -> Notebook Settings

In [6]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [7]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[5., 6.], [7., 8.]])

Addition

In [10]:
a + b

tensor([[ 6.,  8.],
        [10., 12.]])

Element wise multiplication

In [ ]:
print("Element-wise Multiplication:\n", a * b)

Matrix Multiplication

In [11]:
print("Matrix Multiplication:\n" , torch.matmul(a,b))

Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


In [12]:
a.matmul(b)

tensor([[19., 22.],
        [43., 50.]])

In [13]:
b.matmul(a)

tensor([[23., 34.],
        [31., 46.]])

Reshaping tensors. Note the row-column ordering.

In [20]:
tensor = torch.arange(1, 13)  # 1D tensor
print("Original:", tensor)

reshaped = tensor.view(3, 4)
print("Reshaped to 3x4:\n", reshaped)

print("Reshaped to 2x2x3:\n", reshaped.view(2,2,3))

Original: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Reshaped to 3x4:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Reshaped to 2x2x3:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
